
# Calculate average Loading Time and write it to file (only use for finding the right Time, not performance optimized!)
testTime: true

# Spam your Console with EVERY loading Time of EVERY Chunk being loaded (not recommended)
showAllTimes: false


# Maximum Time a Chunk is allowed to load in miliseconds. Make it persistent if it takes longer. 0 = Disable
maxLoadTime: 0

# Maximum amount of persistent Chunks, 0 = Unlimited
maxChunks: 100

# Preload all persistent Chunks when the server starts
Preload: true

# Make Chunks persistent forever if they were over the Timelimit once, even if they are under it in the future.
checkOnce: false

# Autosave interval in minutes, 0 = Disable
autosave: 10

# Disable all Functions for these Worlds
excludedWorlds:
- Example
